version: '4.24.0'
services:
  mysql_server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d