package com.management.app.managemenetapp;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;

/**
 * Singleton class responsible for sending Emails
 */
public class EmailSender {
    private static EmailSender instance;
    private final Session session;
    private final String username = "a618675d59741b";
    private final String password = "0346a738142cea";

    /**
     * Private constructor to prevent external instantiation.
     */
    private EmailSender() {
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
        properties.put("mail.smtp.host", "sandbox.smtp.mailtrap.io");
        properties.put("mail.smtp.port", "2525");

        session = Session.getDefaultInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        session.setDebug(true);
    }

    /**
     * Returns the singleton instance of EmailSender. If the instance is null, a new instance is created.
     *
     * @return The singleton instance of EmailSender.
     */
    public static EmailSender getInstance() {
        if (instance == null) {
            instance = new EmailSender();
        }
        return instance;
    }

    /**
     * sends the Password Recovery Code per Email to the Recipient
     *
     * @param recipient the Receiver Email Address
     * @param code      the 6-digit Recovery Code generated by the Encrypter class
     */
    public void sendRecoveryEmail(String recipient) {
        String emailSubject = Translator.getInstance().translate("PasswordRecoveryEmailSubject");
        String recoveryEmailText = Translator.getInstance().translate("PasswordRecoveryEmailText");
        String defaultSendEmail = "ExamManagementApp@uni-wuppertal.de";
        String code = Encrypter.getInstance().getCurrentCode().getCode();

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(defaultSendEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recipient));
            message.setSubject(emailSubject);
            message.setText(recoveryEmailText + " " + code);
            message.setContent(getHtmlBody(recoveryEmailText, code), "text/html");

            Transport.send(message);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * HTML Email Body Template
     *
     * @param recoveryEmailText the translated email text
     * @param code              the 6-digit Recovery Code
     * @return the HTML Email Body
     */
    private String getHtmlBody(String recoveryEmailText, String code) {
        return String.format("""
                <div style="display: flex; justify-content: center">
                    <div style="display: flex; flex-direction: column">
                        <p style="font-family: Inter, system-ui">%s</p>
                        <div style="display: flex; justify-content: center">
                            <h3 style="font-family: Inter, system-ui; letter-spacing: 5px">%s</h3>
                        </div>
                    </div>
                </div>""", recoveryEmailText, code);
    }
}