USE exam_management_app;

INSERT INTO GradeLimits
SELECT '5.0', 0, 49, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '4.0', 50, 54, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '3.7', 55, 59, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '3.3', 60, 64, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '3.0', 65, 69, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '2.7', 70, 74, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '2.3', 75, 79, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '2.0', 80, 84, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '1.7', 85, 89, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '1.3', 90, 94, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;

INSERT INTO GradeLimits
SELECT '1.0', 95, 100, Id AS ExamId
FROM Exams
WHERE Id BETWEEN 1 AND 36;